{% set name = "emmental" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c4aab60435910c16632b92e37b88962122e4533256075b1efbcab5bb13cc282

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.11
    - pyyaml >=5.1
    - scikit-learn >=0.20.0
    - scipy >=1.1.0
    - tensorboard >=1.15.0
    - pytorch >=1.3.1
    - tqdm >=4.36.0

test:
  imports:
    - emmental
    - emmental.contrib
    - emmental.contrib.slicing
    - emmental.contrib.slicing.modules
    - emmental.logging
    - emmental.metrics
    - emmental.modules
    - emmental.optimizers
    - emmental.schedulers
    - emmental.utils

about:
  home: https://github.com/SenWu/emmental
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for building multi-modal multi-task learning systems.
  doc_url: https://emmental.readthedocs.io/
  dev_url: https://github.com/SenWu/emmental

extra:
  recipe-maintainers:
    - npavlovikj
